sudo: false
language: node_js
node_js:
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
env:
  global:
    # EGG_PASSPORT_TWITTER_CONSUMER_KEY
    - secure: "1ZVGUb8Qw59R+cbqG9AVViYBYD3Rn/5Knwk4x5mYuLIfYuywehiRmTyI5kj50Yq8FDBtHBXNLjDXxsiHeg8mBbkjpG3JQiiiqh5v+Jrha328EyBSKqPC68kgU912YsJ1UfNeDg6Tfy6bixPpz25Iu6ESs/aLVZK6Z6u+usIDaAbMnn2Z+1oKQaWE9WDe3U7EFN3yUMUquJZ++KQ4JidRSDgDE9ofIik7C/9PWr5KDmz3h/0JXn2oxWeXpc/ijhcKXsSMw8pk9qWgfm/E1oZsY0TCJLOjqZ9Ml8WnQ4qe33aGjkE2YflbT95SPCx8D1guwUd8/+Zw1CVQzE1A7sFgCnD6pNey60PH15GosE2OdJjyyaeYtuxrob1j2LB0Ne+H7WReaA5LqsQtzQjMlafCJz7CPMzEgZrEULC8rGr+s927j4KsEOlBlbDyK+WeS9zzfIb5JbEYdDBPROSfurb2/7gSwITdYuj4hRgrTodx93aBMQ1u956BjjJUdl4hcGEGmODTSMvgywlW4lQbChpNRq1dYNYyQWrZmOAmeCdx9lLHYrixBVywtaFCz7jdA+ZsGUJli5BwVx25i1azLZdetXmJPqnDKPo42etZS0SUXanL4LebzrerOk1DeMbfSUurpNLZXWOOGfcWob4lGh9iGstc4ihhJ9c3LUmPIYDi0uQ="
    # EGG_PASSPORT_TWITTER_CONSUMER_SECRET
    - secure: "EEbw+mG+9hhFnT+EmGTY0s0Ym/kM+xZxJuzLTa+tSpnvs8Li8XZUC6RwQ9yvrIcO65vdLqP5Tbo4+Wxti0EXJl6cHDbD9WOQzV+L+JzBJeUS/7BkvLc6SBgs9qafPikdlde3Zmh9yAzfk5xGp1xEdKPM31M0RRwEmN3KBqk+m38tQYrFXL/oRL7cZLSSn3f1yLL7WEwBBJ+vU9Cw8JDt/hxxwtzFTYoZ+FJpbuvH16lrnt9Fm4baCcmoBKAcScSWxfYa328ICz0N/uGCwy5Y4WHp2eXiG1Yoo4YKNJ7pC83qoyvKAHyv1qrZMB/eGGkGKzPFjIEIiuusu9xvCXSI7gNY382rpta914ps0Sb5MwjWCgqGRvPIkiHPPdO/4mCayhl2kKA/AGy3JsRSBvE7EtP9uqdndrJF28U5A5vQ6w/DFAsQKIkVM4frztUBoimE2ZZR+tJZqJUkdVoEXZb9H9YqdDbvfE1IkjfX5DqMQlUkuZ3ATb+oAwApuNZsD6xu7p2KzEnWqMnUyaIYP2pyrrf4KaSdC4CaYfXmCffnxhwQNgnKiZD95zwxL3TFe5p7NAjhMLWb1UaQJ5LB8OoVSbuhV+m0V0jvlNPOKLsNtPVQrQ2v4V/nLAyW+xi5VqzmxNwt5rozyjqMaYZ3gVoC7IdcuEr8dDUb6pFC/CDM+rA="
